### GET test
GET /api/status
Host: localhost:5262
x-api-key: 123

### Send POST request with json body
POST /api/client HTTP/1.1
Host: localhost:5262
x-api-key: 123
Content-Type: application/json
Content-Length: 76

{
  "id": "D3C380CA-8419-4BAF-A08D-F02EC665D355",
  "name": "content",
  "clientType": "Source"
}

### POST Create update
POST /api/status HTTP/1.1
Host: localhost:5262
x-api-key: 123
Content-Type: application/json
Content-Length: 76

{
  "clientId": "D3C380CA-8419-4BAF-A08D-F02EC665D355",
  "date": "2023-12-26T23:03:35.3463826-03:00",
  "deviceStats": [
    {
      "device": "CPU",
      "stat": "Usage",
      "value": "60%"
    },
    {
      "device": "Memory",
      "stat": "Usage",
      "value": "30%"
    },
    {
      "device": "GPU",
      "stat": "Usage",
      "value": "30%"
    }
  ]
}
